name: ChatManagerSpigot
author: Despical
api-version: 1.16
main: me.despical.chatmanager.Main
version: ${project.version}
commands:
  msg:
    aliases: [message, mesaj]
  togglemsg:
    aliases: [toggle, mesajtoggle]
  engelle:
    aliases: [ignoreplayer]
  sohbet:
  sohbetsil: